begin;

create table public.rank_system_versions (
    id uuid primary key default gen_random_uuid(),
    version_number bigint generated by default as identity unique not null,
    name text not null,
    description text,
    formula_key text not null,
    input_schema_version integer not null,
    term_schema_version integer not null,
    rubric_version integer not null,
    rubric_semantics_key text not null,
    contract jsonb not null,
    contract_hash text not null unique,
    created_by text,
    created_at timestamptz not null default now(),
    constraint rank_system_versions_version_positive
        check (version_number >= 1),
    constraint rank_system_versions_name_bounded
        check (length(name) between 1 and 128),
    constraint rank_system_versions_description_bounded
        check (description is null or length(description) <= 4096),
    constraint rank_system_versions_formula_key_bounded
        check (length(formula_key) between 1 and 128),
    constraint rank_system_versions_schema_versions_positive
        check (input_schema_version >= 1 and term_schema_version >= 1),
    constraint rank_system_versions_rubric_version_positive
        check (rubric_version >= 1),
    constraint rank_system_versions_rubric_semantics_bounded
        check (length(rubric_semantics_key) between 1 and 128),
    constraint rank_system_versions_contract_valid
        check (jsonb_typeof(contract) = 'object'
               and pg_catalog.pg_column_size(contract) <= 32768),
    constraint rank_system_versions_hash_valid
        check (contract_hash ~ '^sha256:[0-9a-f]{64}$'),
    constraint rank_system_versions_created_by_bounded
        check (created_by is null or length(created_by) <= 256)
);

comment on table public.rank_system_versions is
    'Immutable semantic contracts for ranking. Formula dials and data choices belong to rank_experiments; incompatible input, term, formula, or rubric semantics create a new version.';
comment on column public.rank_system_versions.version_number is
    'Locally allocated monotonic display version. Hosted mirrors preserve this number and never allocate versions independently.';

insert into public.rank_system_versions (
    id, name, description, formula_key, input_schema_version,
    term_schema_version, rubric_version, rubric_semantics_key, contract,
    contract_hash, created_by
) values (
    '00000000-0000-4000-8000-00000000a001',
    'v1',
    'Current five-term rank formula: rubric/prior, agency, feed, source authority, freshness.',
    'compute_rank_key_v1',
    1,
    1,
    1,
    'newsworthiness_boolean_v1',
    '{
        "formula_key":"compute_rank_key_v1",
        "input_schema_version":1,
        "ordered_term_keys":[
            "rubric_points","agency_term","feed_term","source_term","freshness_term"
        ],
        "rubric_semantics_key":"newsworthiness_boolean_v1",
        "rubric_version":1,
        "term_schema_version":1
    }'::jsonb,
    'sha256:871a8014438913574a0939b89c4c2d4e6b8a70a1cf38f908791f0bfcd77079f4',
    'migration'
);

create function public.reject_rank_system_version_mutation()
returns trigger
language plpgsql
set search_path = ''
as $fn$
begin
    raise exception 'rank system versions are immutable'
        using errcode = '55000';
end;
$fn$;

create trigger rank_system_versions_immutable
before update or delete on public.rank_system_versions
for each row execute function public.reject_rank_system_version_mutation();

create table public.rank_experiments (
    id uuid primary key default gen_random_uuid(),
    rank_system_version_id uuid not null
        references public.rank_system_versions(id),
    name text not null,
    pipeline_namespace text not null,
    source_run_id uuid,
    parent_experiment_id uuid references public.rank_experiments(id),
    rerun_of_experiment_id uuid references public.rank_experiments(id),
    status text not null default 'draft',
    validation_profile text not null default 'full',
    config jsonb not null,
    config_hash text not null,
    preprocessing_config jsonb not null default '{}'::jsonb,
    data_cutoff_at timestamptz,
    data_snapshot_hash text,
    context_set_hash text,
    code_commit text,
    metrics jsonb,
    failure_reason text,
    started_at timestamptz,
    finished_at timestamptz,
    created_at timestamptz not null default now(),
    unique (id, rank_system_version_id),
    constraint rank_experiments_name_bounded
        check (length(name) between 1 and 128),
    constraint rank_experiments_namespace_valid
        check (pipeline_namespace in ('complex_v1', 'simple_v1', 'legacy_import')),
    constraint rank_experiments_status_valid
        check (status in (
            'draft', 'running', 'calculated', 'validated', 'rejected',
            'failed', 'promoted'
        )),
    constraint rank_experiments_validation_profile_valid
        check (validation_profile in ('full', 'legacy_import')),
    constraint rank_experiments_legacy_profile_consistent
        check (validation_profile <> 'legacy_import'
               or pipeline_namespace = 'legacy_import'),
    constraint rank_experiments_config_valid
        check (jsonb_typeof(config) = 'object'
               and pg_catalog.pg_column_size(config) <= 65536),
    constraint rank_experiments_preprocessing_valid
        check (jsonb_typeof(preprocessing_config) = 'object'
               and pg_catalog.pg_column_size(preprocessing_config) <= 65536),
    constraint rank_experiments_config_hash_valid
        check (config_hash ~ '^sha256:[0-9a-f]{64}$'),
    constraint rank_experiments_data_hash_valid
        check (data_snapshot_hash is null
               or data_snapshot_hash ~ '^(sha256|legacy):[0-9a-z-]+$'),
    constraint rank_experiments_context_hash_valid
        check (context_set_hash is null
               or context_set_hash ~ '^(sha256|legacy):[0-9a-z-]+$'),
    constraint rank_experiments_code_commit_bounded
        check (code_commit is null or length(code_commit) <= 128),
    constraint rank_experiments_metrics_valid
        check (metrics is null or (
            jsonb_typeof(metrics) = 'object'
            and pg_catalog.pg_column_size(metrics) <= 131072
        )),
    constraint rank_experiments_failure_bounded
        check (failure_reason is null or length(failure_reason) <= 4096),
    constraint rank_experiments_window_valid
        check (started_at is null or finished_at is null or started_at <= finished_at)
);

comment on table public.rank_experiments is
    'One immutable ranking configuration and result cohort. source_run_id plus pipeline_namespace identifies its clustering input without coupling ranking history to deletable source-run tables.';
comment on column public.rank_experiments.validation_profile is
    'full for every normal experiment. legacy_import is a one-time order-preserving bootstrap exemption and cannot validate future candidates.';

create unique index rank_experiments_one_legacy_import_idx
    on public.rank_experiments (validation_profile)
    where validation_profile = 'legacy_import';
create index rank_experiments_source_run_idx
    on public.rank_experiments (pipeline_namespace, source_run_id)
    where source_run_id is not null;
create index rank_experiments_created_idx
    on public.rank_experiments (created_at desc, id);

create function public.protect_rank_experiment_payload()
returns trigger
language plpgsql
set search_path = ''
as $fn$
begin
    if new.id is distinct from old.id
       or new.rank_system_version_id is distinct from old.rank_system_version_id
       or new.name is distinct from old.name
       or new.pipeline_namespace is distinct from old.pipeline_namespace
       or new.source_run_id is distinct from old.source_run_id
       or new.parent_experiment_id is distinct from old.parent_experiment_id
       or new.rerun_of_experiment_id is distinct from old.rerun_of_experiment_id
       or new.validation_profile is distinct from old.validation_profile
       or new.config is distinct from old.config
       or new.config_hash is distinct from old.config_hash
       or new.preprocessing_config is distinct from old.preprocessing_config
       or new.data_cutoff_at is distinct from old.data_cutoff_at
       or new.data_snapshot_hash is distinct from old.data_snapshot_hash
       or new.context_set_hash is distinct from old.context_set_hash
       or new.code_commit is distinct from old.code_commit
       or new.started_at is distinct from old.started_at
       or new.created_at is distinct from old.created_at then
        raise exception 'rank experiment inputs and provenance are immutable'
            using errcode = '55000';
    end if;
    return new;
end;
$fn$;

create trigger rank_experiments_payload_immutable
before update on public.rank_experiments
for each row execute function public.protect_rank_experiment_payload();

create table public.snapshot_rank_rows (
    experiment_id uuid not null,
    rank_system_version_id uuid not null,
    golden_event_card_id uuid not null,
    storyline_id uuid not null,
    category_id uuid,
    theme_id uuid,
    agency_ids text[] not null default '{}',
    global_position integer not null,
    category_position integer,
    primary_rank_key float8 not null,
    context_hash text not null,
    rank_input jsonb,
    rank_input_hash text,
    rank_terms jsonb,
    formula_trace jsonb,
    card_snapshot jsonb not null,
    context_snapshot jsonb,
    created_at timestamptz not null default now(),
    primary key (experiment_id, rank_system_version_id, golden_event_card_id),
    foreign key (experiment_id, rank_system_version_id)
        references public.rank_experiments(id, rank_system_version_id),
    unique (experiment_id, rank_system_version_id, storyline_id),
    unique (experiment_id, rank_system_version_id, global_position),
    unique (experiment_id, rank_system_version_id, category_id, category_position),
    constraint snapshot_rank_rows_global_position_positive
        check (global_position >= 1),
    constraint snapshot_rank_rows_category_position_valid
        check ((category_id is null and category_position is null)
               or (category_id is not null and category_position >= 1)),
    constraint snapshot_rank_rows_rank_key_finite
        check (primary_rank_key > '-Infinity'::float8
               and primary_rank_key < 'Infinity'::float8),
    constraint snapshot_rank_rows_context_hash_valid
        check (context_hash ~ '^(md5:[0-9a-f]{32}|sha256:[0-9a-f]{64}|legacy:[0-9a-z-]+)$'),
    constraint snapshot_rank_rows_input_consistent
        check ((rank_input is null) = (rank_input_hash is null)),
    constraint snapshot_rank_rows_input_valid
        check (rank_input is null or (
            jsonb_typeof(rank_input) = 'object'
            and pg_catalog.pg_column_size(rank_input) <= 65536
        )),
    constraint snapshot_rank_rows_input_hash_valid
        check (rank_input_hash is null
               or rank_input_hash ~ '^sha256:[0-9a-f]{64}$'),
    constraint snapshot_rank_rows_terms_valid
        check (rank_terms is null or (
            jsonb_typeof(rank_terms) = 'object'
            and pg_catalog.pg_column_size(rank_terms) <= 32768
        )),
    constraint snapshot_rank_rows_formula_trace_valid
        check (formula_trace is null or (
            jsonb_typeof(formula_trace) = 'object'
            and pg_catalog.pg_column_size(formula_trace) <= 65536
        )),
    constraint snapshot_rank_rows_card_snapshot_valid
        check (jsonb_typeof(card_snapshot) = 'object'
               and pg_catalog.pg_column_size(card_snapshot) <= 262144),
    constraint snapshot_rank_rows_context_snapshot_valid
        check (context_snapshot is null or (
            jsonb_typeof(context_snapshot) = 'object'
            and pg_catalog.pg_column_size(context_snapshot) <= 262144
        ))
);

comment on table public.snapshot_rank_rows is
    'One immutable frozen ranked overview per storyline in an experiment cohort. Card/context payloads are denormalized and card IDs intentionally have no FK to the rewriteable golden mirror.';

create index snapshot_rank_rows_category_idx
    on public.snapshot_rank_rows (
        experiment_id, rank_system_version_id, category_id, category_position
    );
create index snapshot_rank_rows_theme_idx
    on public.snapshot_rank_rows (
        experiment_id, rank_system_version_id, theme_id, primary_rank_key desc
    );
create index snapshot_rank_rows_agencies_idx
    on public.snapshot_rank_rows using gin (agency_ids);

create table public.rank_position_opinions (
    experiment_id uuid not null,
    rank_system_version_id uuid not null,
    golden_event_card_id uuid not null,
    category_id uuid not null,
    current_category_position integer not null,
    suggested_category_position integer,
    position_delta integer,
    direction text not null,
    status text not null,
    reason text,
    neighbor_card_ids uuid[] not null default '{}',
    comparison_evidence jsonb not null default '[]'::jsonb,
    consistent_comparisons integer not null default 0,
    total_comparisons integer not null default 0,
    judge_model text,
    prompt_version integer,
    input_hash text,
    created_at timestamptz not null default now(),
    primary key (experiment_id, rank_system_version_id, golden_event_card_id),
    foreign key (experiment_id, rank_system_version_id, golden_event_card_id)
        references public.snapshot_rank_rows(
            experiment_id, rank_system_version_id, golden_event_card_id
        ),
    constraint rank_position_opinions_positions_valid
        check (current_category_position >= 1
               and (suggested_category_position is null
                    or suggested_category_position >= 1)),
    constraint rank_position_opinions_direction_valid
        check (direction in ('up', 'down', 'stay', 'uncertain')),
    constraint rank_position_opinions_status_valid
        check (status in (
            'available', 'bounded', 'not_run', 'insufficient_neighbors',
            'inconsistent', 'failed'
        )),
    constraint rank_position_opinions_available_consistent
        check (status <> 'available' or (
            suggested_category_position is not null
            and position_delta = suggested_category_position - current_category_position
        )),
    constraint rank_position_opinions_bounded_consistent
        check (status <> 'bounded' or (
            suggested_category_position is null
            and position_delta is not null
            and position_delta <> 0
            and direction in ('up', 'down')
        )),
    constraint rank_position_opinions_direction_consistent
        check (
            (direction = 'up' and position_delta < 0)
            or (direction = 'down' and position_delta > 0)
            or (direction = 'stay' and position_delta = 0)
            or (direction = 'uncertain' and position_delta is null)
        ),
    constraint rank_position_opinions_reason_bounded
        check (reason is null or length(reason) <= 4096),
    constraint rank_position_opinions_evidence_valid
        check (jsonb_typeof(comparison_evidence) = 'array'
               and pg_catalog.pg_column_size(comparison_evidence) <= 131072),
    constraint rank_position_opinions_counts_valid
        check (consistent_comparisons >= 0
               and total_comparisons >= consistent_comparisons),
    constraint rank_position_opinions_model_bounded
        check (judge_model is null or length(judge_model) <= 256),
    constraint rank_position_opinions_prompt_valid
        check (prompt_version is null or prompt_version >= 1),
    constraint rank_position_opinions_input_hash_valid
        check (input_hash is null or input_hash ~ '^sha256:[0-9a-f]{64}$')
);

comment on table public.rank_position_opinions is
    'Immutable category-relative LLM placement recommendation. bounded means every inspected neighbor should be crossed but the audit window ended before an exact destination was proven.';

create table public.golden_rank_state (
    id text primary key default 'primary',
    active_experiment_id uuid not null,
    active_rank_system_version_id uuid not null,
    activated_at timestamptz not null default now(),
    activated_by text,
    constraint golden_rank_state_singleton check (id = 'primary'),
    constraint golden_rank_state_activated_by_bounded
        check (activated_by is null or length(activated_by) <= 256),
    foreign key (active_experiment_id, active_rank_system_version_id)
        references public.rank_experiments(id, rank_system_version_id)
);

comment on table public.golden_rank_state is
    'Database-enforced zero-or-one singleton pointer selecting the complete active ranking experiment. Direct writes are revoked; promotion RPCs own changes.';

create view public.golden_rank_rows
with (security_invoker = true)
as
select
    ranked.golden_event_card_id,
    ranked.storyline_id,
    ranked.primary_rank_key,
    ranked.rank_terms,
    ranked.rank_input,
    ranked.context_hash,
    ranked.card_snapshot,
    ranked.context_snapshot,
    ranked.global_position,
    ranked.category_id,
    ranked.category_position,
    ranked.experiment_id,
    ranked.rank_system_version_id
from public.golden_rank_state active
join public.snapshot_rank_rows ranked
  on ranked.experiment_id = active.active_experiment_id
 and ranked.rank_system_version_id = active.active_rank_system_version_id;

comment on view public.golden_rank_rows is
    'Active immutable rank rows selected atomically by golden_rank_state. primary_rank_key is derived from the selected experiment, never copied back into golden cards.';

create function public.reject_immutable_rank_result_mutation()
returns trigger
language plpgsql
set search_path = ''
as $fn$
begin
    raise exception 'rank result rows are immutable'
        using errcode = '55000';
end;
$fn$;

create trigger snapshot_rank_rows_immutable
before update or delete on public.snapshot_rank_rows
for each row execute function public.reject_immutable_rank_result_mutation();

create trigger rank_position_opinions_immutable
before update or delete on public.rank_position_opinions
for each row execute function public.reject_immutable_rank_result_mutation();

alter table public.rank_system_versions enable row level security;
alter table public.rank_experiments enable row level security;
alter table public.snapshot_rank_rows enable row level security;
alter table public.rank_position_opinions enable row level security;
alter table public.golden_rank_state enable row level security;

revoke all privileges on table
    public.rank_system_versions,
    public.rank_experiments,
    public.snapshot_rank_rows,
    public.rank_position_opinions,
    public.golden_rank_state
    from public, anon, authenticated, service_role;

grant select, insert on table
    public.rank_system_versions,
    public.rank_experiments,
    public.snapshot_rank_rows,
    public.rank_position_opinions
    to service_role;
grant select on table public.golden_rank_state to service_role;
grant select on table public.golden_rank_rows to service_role;
grant usage, select on sequence public.rank_system_versions_version_number_seq
    to service_role;

revoke all on function public.reject_rank_system_version_mutation()
    from public, anon, authenticated, service_role;
revoke all on function public.protect_rank_experiment_payload()
    from public, anon, authenticated, service_role;
revoke all on function public.reject_immutable_rank_result_mutation()
    from public, anon, authenticated, service_role;

commit;
